version: 0.0.{build}
max_jobs: 1
image: Visual Studio 2017
clone_folder: C:\prj\test-appveyor
build_script:
- cmd: >-
    SET

    SET PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%path%

    cd C:\prj\test-appveyor

    c:\Python36-x64\python --version

    c:\Python36-x64\python -m pip list
    
    c:\Python36-x64\python -m virtualenv venv

    venv\Scripts\activate

    python -m pip install "pip<19.0"

    pip list

    pip install -r requirements.txt

    pip install pyinstaller

    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    cl.exe /D_USRDLL /D_WINDLL deca/process_image.c /link /DLL /OUT:process_image.dll

    pyinstaller process_avtx.py

artifacts:
- path: dist\process_avtx

deploy:
  artifact: dist\process_avtx
  prerelease: true
  description: 'Test Release'
  provider: GitHub
  auth_token:
    secure: gb7NBwSinsyPgvJSkCDgUNjxAzqCqRbPEN3b0oX1XF92PAxuy2Opyk+Rbvw660R3
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
