version: 0.0.{build}
max_jobs: 1
image: Visual Studio 2017
clone_folder: C:\prj\test-appveyor
build_script:
- cmd: >-
    cd C:\prj\test-appveyor

    c:\Python36-x64\python -m pip list
    
    c:\Python36-x64\python -m virtualenv venv

    venv\Scripts\activate

    python -m pip install "pip<19.0"

    pip list

    rem pip install -r requirements.txt

    rem pip install pyinstaller

    rem "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    rem cl.exe /D_USRDLL /D_WINDLL deca/process_image.c /link /DLL /OUT:process_image.dll

    rem pyinstaller process_avtx.py

artifacts:
- path: dist\process_avtx.zip

